### ISSUE TITLE
Native image building throws ClassNotFoundException for org.reactivestreams.Publisher even though no reactor code is used

### ISSUE THREAD

**Issue by mminella** [spring-projects-experimental/spring-graal-native#97] opened 2020-04-14 02:35 UTC
When running a Spring Batch example (the `spring-batch` sample found in this branch: https://github.com/mminella/spring-graal-native/tree/batch-sample ), if you remove the dependency on `reactive-streams` from the POM, you get the exception:

```
Fatal error: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:357)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:501)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
Caused by: java.lang.NoClassDefFoundError: org/reactivestreams/Publisher
	at jdk.vm.ci.hotspot.CompilerToVM.getDeclaredMethods(Native Method)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:952)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.declaresDefaultMethods(ClassInitializationFeature.java:375)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.hasDefaultMethods(ClassInitializationFeature.java:363)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.buildClassInitializationInfo(ClassInitializationFeature.java:351)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:193)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:715)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:715)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.reactivestreams.Publisher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 16 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1527)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1289)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1250)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1209)

real	0m24.482s
user	1m28.095s
sys	0m3.743s
FAILURE: an error occurred when compiling the native-image.
```
My hunch is that it has to do with the Spring Boot provided auto configuration for transaction managers which has both reactive and non-reactive options in the same class here: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/transaction/TransactionAutoConfiguration.java

**Comment by sdeleuze** [comment] 2020-04-14 09:22
Good catch, that seems something to explore, [`org.springframework.transaction.annotation.Hints`](https://github.com/spring-projects-experimental/spring-graal-native/blob/master/spring-graal-native-configuration/src/main/java/org/springframework/transaction/annotation/Hints.java) seems indeed to activate both reactive and non-reactive transaction support via [`TransactionAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/transaction/TransactionAutoConfiguration.java).

@aclement Do you think making the configuration hints more clever by understanding `@ConditionalOnSingleCandidate(ReactiveTransactionManager.class)` could be doable?

**Comment by sdeleuze** [comment] 2020-04-14 09:32
Also, this issue can be easily reproduced by removing the `reactive-streams` dependency from `spring-petclinic-jpa` sample.

**Comment by aclement** [comment] 2020-04-16 21:07
I think this is what I've just raised as https://github.com/oracle/graal/issues/2355 - I don't think it is our code. I've seen some situations like this before with enums. This time it is default methods.

**Comment by aclement** [comment] 2020-04-16 22:18
Confirmed with Esteban, this is fixed in 20.1 dev builds right now (I tested vanilla-tx). So we can remove those deps when we adopt that.

**Comment by aclement** [comment] 2020-04-17 00:54
So this turned out to be kind of what I expected (hoped!), not us. We absolutely don't try to be smart in the feature. The act of opening up a type for reflection would only have an affect if that type is available for reflection. So we can't accidentally make something appear that would lead down a reactive path, if the underlying types to make that happen aren't around.

This is very like an enum problem we had many months ago where we needed to include a load of extraneous stuff on the classpath because graals resolution of enum values wasn't coping with them missing.

So, to answer Sebastiens question - should we make the hints smart enough to understand `ConditionalOnSingleCandidate`? I would say only from a class point of view, never cross that line to trying to work out what beans are available, that is duplicating spring.   In terms of a class understanding, if it is `@ConditionalOnSingleCandidate(SomeClass)` and SomeClass isn't on the classpath, there can't be a single candidate. Done. But if it is around, i would not try to work out how many candidates there are.  This treatment is what causes us to produce larger images because we are never quite as optimal as the agent, but the trade off is you don't have to run the app to build an image. 

At that is really the level of 'smarts' across the board (except for one case I'll cover below). Treating all conditions like that: if they refer to types that aren't around, those conditions are not going to pass.  Is there a condition this breaks down for? Maybe, let me know!

That said, there is one more thing we should revisit before 0.7, I'll raise an issue - it is the smarts around ConditionalOnProperty. We currently have a little bit of code i there was being a bit eager checking ConditionalOnProperty - and due to the spring flexibility for property sources, its no good, we should get rid of it (yes image sizes are likely to increase). That is another example of being too smart.

**Comment by sdeleuze** [comment] 2020-04-17 13:04
Thanks for finding the root cause!

**Closed** 2020-05-05 16:34 UTC
Labels: status: in-progress, type: compatibility
